### ISSUE TITLE
How to use windsurf in my repo

### ISSUE THREAD

**Issue by hanckmann** [KenMacD/etc-nixos#1]
Hi,

It would be great to use your nix file for windsurf in my configuration.
However, I do not get it done.

I am a NixOS user for about two years, but I do not understand everything about it (at all).
My system is based on flakes (with home-manager). I have a single flake which uses (only) the 24.11 channel.
I never made any custom packages.

Furthermore, I have tried to follow the thread of how you integrated the windsurf package into your configuration and flake, but your configuration is much more complicated than mine... so I basically always end up with errors.

Is it possible to publish this package as a stand-alone flake so I can include it and/or can you help me on how to get it integrated into my config?

I hope you do not mind me asking this advice...

**Comment by KenMacD** [comment]
Hi! No worries on asking for advice. Half my config probably comes from random advice and `path:*.nix <blah>` searches on Github.

That windsurf code is a little rough as I figured it wouldn't be long until someone packaged it for Nix.  Also I haven't been including a `flake.lock` in my pushed versions as I wanted to reduce the noise from updating it so it's not all the straightforward to make it a stand-alone flake.

I don't suppose you post your nixos configs anywhere? I took a quick look but didn't see it in your repos.

Not sure if this helps, but I'm thinking this might be enough to get it working. I'm going to assume you have the somewhat standard `flake.nix` with a `nixpkgs` input.

* Download the `windsurf.nix` file and put it in the same place as your `flake.nix` file for you host
* Find your `nixpkgs.lib.nixosSystem` config for your host
* Add `nixpkgs` to the `specialArgs` in that host config so that `nixpkgs` is available to modules
* Add a new module to the modules section of that config that should look like:

```nix
        modules = [
          ({...}: {
            environment.systemPackages = [
              (pkgs.callPackage ./windsurf.nix {inherit nixpkgs;})
            ];
          })
```

A couple of notes based on my understanding of how things work (I wouldn't call my self an expert on NixOS either):

* The `inherit nixpkgs;` is just shorthand for `nixpkgs=nixpkgs`, and is just there because Windsurf needs to build itself like it's another variant of vscode.
* The brackets around the the callPackage is important to make sure it actually builds/uses the resulting package
* Passing values in `specialArgs` lets you use them in modules, but I'm not sure if passing `inputs` and using `inputs.nixpkgs` is better or worse than passing `nixpkgs `directly

Anyway, let me know if this works for you, or what errors  you get if it doesn't. Good luck!

**Comment by hanckmann** [comment]
Thank you for your explanation. I learned a lot and I got windsurf installed correctly.

The only change I had to make was adding `pkgs` to the input list:

```
          ({pkgs, ...}: {
            environment.systemPackages = [
              (pkgs.callPackage (self + "/configs/packages/windsurf.nix") {inherit nixpkgs;})
            ];
          })
```

The reason I do not (yet) publish my config files is that I have not (yet) found the time to securely store all my secrets. I see you use sops for this. I guess that might be a nice thing to do over the holiday season :-)

Thanks for your help!
